
server:
  port: 8889

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jpa:
    properties:
      hibernate:
        multiTenancy: SCHEMA
        format_sql: true
    hibernate:
      ddl-auto: none